# Generated by Django 3.2.18 on 2023-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pessoas_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
